server:
  port: 8888

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RainZeroAPTX4869/springcloud-config.git  #git的仓库地址
          search-paths:   #搜索目录
            - springcloud-config
          username: 2368001047@qq.com
          password: rz19960604
      label: master   #读取的分支
  rabbitmq:
    host: 192.168.0.200  #本机写localhost，服务器的写服务器地址
    port: 5672   #客户端和RabbitMQ进行通信的端口
    username: admin #默认也是guest
    password: admin #默认也是guest

#RabbitMQ相关配置
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka   #服务注册到的eureka地址
